/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Client;

import java.net.DatagramPacket;
import java.net.DatagramSocket;
import java.net.InetAddress;
import javax.swing.JOptionPane;
import Client.ValidateData;

/**
 *
 * @author laihu
 */
public class Input_Information_Form extends javax.swing.JFrame {

    /**
     * Creates new form Input_Information_Form
     */
    public Input_Information_Form() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Name_txt = new javax.swing.JTextField();
        MSSV_txt = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Mathpoint_txt = new javax.swing.JTextField();
        Literaturepoint_txt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Englishpoint_txt = new javax.swing.JTextField();
        Send_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Họ và Tên");

        jLabel2.setText("MSSV");

        jLabel3.setText("Điểm Toán");

        jLabel4.setText("Điểm Văn");

        Mathpoint_txt.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        Literaturepoint_txt.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel5.setText("Điểm Anh Văn");

        Englishpoint_txt.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Mathpoint_txt)
                            .addComponent(Literaturepoint_txt)
                            .addComponent(Englishpoint_txt)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(129, 129, 129))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Mathpoint_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addGap(11, 11, 11)
                .addComponent(Literaturepoint_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Englishpoint_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Send_btn.setText("Gửi");
        Send_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Send_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Name_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(MSSV_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(29, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Send_btn)
                .addGap(165, 165, 165))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Name_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MSSV_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Send_btn)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Send_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Send_btnActionPerformed
        // TODO add your handling code here:
        //Gửi dữ liệu gồm TÊN, MSSV, ĐIỂM
        //Bước 1: Mã Hóa dữ liệu bằng hàm của thằng Phòng
        //Bước 2: Tạo DatagramSocket
        //Bước 3: Tạo biến chuỗi để chứa tất cả dữ liệu cần gửi
        //Bước 4: Tạo DatagramPacket để chứa thông tin gửi (Chuỗi, độ dài chuỗi, ipserver,port)
        //Bước 5: Gửi
        //Bước 6: Nhận respone từ server

        /*Code mẫu
        try {
            DatagramSocket socket = new DatagramSocket();
            String diachi = this.txtdiachi.getText();
            InetAddress ipServer = InetAddress.getByName(diachi);
            int port = 1234;
            String Send = this.txtchuoi.getText();  //>>/// Thằng này chứa thông tin gửi
            sendData = Send.getBytes();

            DatagramPacket sendPacket = new DatagramPacket(sendData, sendData.length, ipServer, port);
            socket.send(sendPacket);

            byte[] buffer = new byte[65507];
            DatagramPacket receivePacket = new DatagramPacket(buffer, buffer.length);
            socket.receive(receivePacket);
            txtketqua.setText(new String(receivePacket.getData()).trim());
            socket.close();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.toString());
        }
         */
        byte[] sendData;
        try {
            DatagramSocket socket = new DatagramSocket();
            String diachi = Input_Address_To_UDP_Server.IPAddress;
            InetAddress ipServer = InetAddress.getByName(diachi);
            int port = Input_Address_To_UDP_Server.PORT;

            //Validate trước
            if (Name_txt.getText().isEmpty() || MSSV_txt.getText().isEmpty() || Mathpoint_txt.getText().isEmpty() || Literaturepoint_txt.getText().isEmpty() || Englishpoint_txt.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Bạn cần nhập đầy đủ thông tin", "Thiếu thông tin", JOptionPane.WARNING_MESSAGE);
            } else {
                if (MSSV_txt.getText().length() != 10) {
                    JOptionPane.showMessageDialog(null, "Mã số sinh viên của bạn bị thiếu", "Sai MSSV", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    if (ValidateData.isSubjectPoint(Mathpoint_txt.getText()) && ValidateData.isSubjectPoint(Literaturepoint_txt.getText()) && ValidateData.isSubjectPoint(Englishpoint_txt.getText())) {
                        String chuoi = "";
                        chuoi =  Name_txt.getText()+"/"+ MSSV_txt.getText()+"/"+ Mathpoint_txt.getText()+"/"+ Literaturepoint_txt.getText()+"/"+ Englishpoint_txt.getText();
                        System.out.println("Chuỗi gửi: "+ chuoi);
                        String Send = chuoi;  //>>/// Thằng này chứa thông tin gửi
                        sendData = Send.getBytes();

                        DatagramPacket sendPacket = new DatagramPacket(sendData, sendData.length, ipServer, port);
                        //Todo: Xong r Tấn m nhận cái này ở main luôn dùm t :))
                        socket.send(sendPacket);
//                        byte[] buffer = new byte[65507];
//                        DatagramPacket receivePacket = new DatagramPacket(buffer, buffer.length);
//                        socket.receive(receivePacket);
//                        txtketqua.setText(new String(receivePacket.getData()).trim());
                        socket.close();
                    } else {
                        JOptionPane.showMessageDialog(null, "Điểm phải là 1 Số lớn hơn 0 và bé hơn 10", "Nhập sai thông tin", JOptionPane.WARNING_MESSAGE);
                    }
                }

            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_Send_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Input_Information_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Input_Information_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Input_Information_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Input_Information_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Input_Information_Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Englishpoint_txt;
    private javax.swing.JTextField Literaturepoint_txt;
    private javax.swing.JTextField MSSV_txt;
    private javax.swing.JTextField Mathpoint_txt;
    private javax.swing.JTextField Name_txt;
    private javax.swing.JButton Send_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
